name: Run nbconvert

on:
  push:
    branches:
      - main

jobs:
  convert_notebooks:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Configure Git
        run: |
          git config user.email "dinellimichele00@gmail.com"
          git config user.name "micheledinelli"

      - name: Install dependencies
        run: |
          pip install nbconvert

      - name: Run nbconvert
        run: ./readme-gen.sh

      - name: Push changes
        run: |
          git add README.md
          git add text-distance-analysis_files
          git add text-representation-analysis_files
          git commit -m "Update README after notebook conversion"
          git push https://$GH_TOKEN@github.com/micheledinelli/text-distances.git HEAD:main
