name: Run nbconvert

on:
  push:
    branches:
      - main

jobs:
  convert_notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install nbconvert

      - name: Run nbconvert
        run: |
          # Convert the notebook to markdown and update README
          jupyter nbconvert --to markdown text-distance-analysis.ipynb --output README.md

          # Append a message to the README
          echo 'Notebooks have been converted and README has been updated.' >> README.md

          # Commit the changes
          git add README.md
          git commit -m "Update README after notebook conversion"
          git push
